=== 19maximilian98/Gaalop/algebras.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/algebras.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE algebras SYSTEM "algebras.dtd">

    <algebras>
    ...
    </algebras>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT algebras (algebra)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT algebra (description|definition)*>
<!ATTLIST algebra
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT definition (transformations|signature|bases)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT bases (plusMinus|zeroInf)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT zeroInf (baseVector)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT baseVector EMPTY>
<!ATTLIST baseVector
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plusMinus (baseVector)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT signature (square)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT square EMPTY>
<!ATTLIST square
    value CDATA #IMPLIED
    baseVector CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT transformations (plusMinusToZeroInf|zeroInfToPlusMinus)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT zeroInfToPlusMinus (equation)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT equation (summand)*>
<!ATTLIST equation
    lhsBaseVector CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT summand EMPTY>
<!ATTLIST summand
    baseVector CDATA #IMPLIED
    weight CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plusMinusToZeroInf (equation)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (long|short)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT short EMPTY>
<!ATTLIST short
    value CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT long EMPTY>
<!ATTLIST long
    value CDATA #IMPLIED
  >

=== 19maximilian98/Gaalop/algebras.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE algebras SYSTEM "algebras.dtd">
<algebras>
    <algebra name="2d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="1"/>
            </signature>
            <transformations>
            </transformations>
        </definition>
        <description>
            <short value="2d GA" />
            <long value="Base vectors: e1,e2. Signature: {1,1}"/>
        </description>
    </algebra>    
    
    <algebra name="3d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="1"/>
                <square baseVector="e3" value="1"/>
            </signature>
            <transformations>
            </transformations>
        </definition>
        <description>
            <short value="3d GA" />
            <long value="Base vectors: e1,e2,e3. Signature: {1,1,1}"/>
        </description>
    </algebra>
    
    <algebra name="cr4d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="einf"/>
                    <baseVector name="e0"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="ep"/>
                    <baseVector name="em"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="1"/>
                <square baseVector="ep" value="1"/>
                <square baseVector="em" value="-1"/>
            </signature>
            <transformations>
                <zeroInfToPlusMinus>
                    <equation lhsBaseVector="ep">
                        <summand weight="0.5" baseVector="einf"/>
                        <summand weight="-1" baseVector="e0"/>
                    </equation>
                    <equation lhsBaseVector="em">
                        <summand weight="0.5" baseVector="einf"/>
                        <summand weight="1" baseVector="e0"/>
                    </equation>
                </zeroInfToPlusMinus>
                <plusMinusToZeroInf>
                    <equation lhsBaseVector="einf">
                        <summand weight="1" baseVector="em"/>
                        <summand weight="1" baseVector="ep"/>
                    </equation>
                    <equation lhsBaseVector="e0">
                        <summand weight="0.5" baseVector="em"/>
                        <summand weight="-0.5" baseVector="ep"/>
                    </equation>
                </plusMinusToZeroInf>
            </transformations>
        </definition>
        <description>
            <short value="4d Compass-Ruler" />
            <long value="Base vectors: e1,e2,einf,e0. Signature: {1,1,1,-1}"/>
        </description>
    </algebra>
    
    <algebra name="pr4d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="1"/>
                <square baseVector="e3" value="1"/>
                <square baseVector="e4" value="1"/>
            </signature>
            <transformations>
            </transformations>
        </definition>
        <description>
            <short value="4d Projective" />
            <long value="Base vectors: e1,e2,e3,e4. Signature: {1,1,1,1}"/>
        </description>
    </algebra>
    
    <algebra name="st4d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="-1"/>
                <square baseVector="e3" value="-1"/>
                <square baseVector="e4" value="-1"/>
            </signature>
            <transformations>
            </transformations>
        </definition>
        <description>
            <short value="4d Space-time" />
            <long value="Base vectors: e1,e2,e3,e4. Signature: {1,-1,-1,-1}"/>
        </description>
    </algebra>
    
    <algebra name="5d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="einf"/>
                    <baseVector name="e0"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="ep"/>
                    <baseVector name="em"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
                <square baseVector="e2" value="1"/>
                <square baseVector="e3" value="1"/>
                <square baseVector="ep" value="1"/>
                <square baseVector="em" value="-1"/>
            </signature>
            <transformations>
                <zeroInfToPlusMinus>
                    <equation lhsBaseVector="ep">
                        <summand weight="0.5" baseVector="einf"/>
                        <summand weight="-1" baseVector="e0"/>
                    </equation>
                    <equation lhsBaseVector="em">
                        <summand weight="0.5" baseVector="einf"/>
                        <summand weight="1" baseVector="e0"/>
                    </equation>
                </zeroInfToPlusMinus>
                <plusMinusToZeroInf>
                    <equation lhsBaseVector="einf">
                        <summand weight="1" baseVector="em"/>
                        <summand weight="1" baseVector="ep"/>
                    </equation>
                    <equation lhsBaseVector="e0">
                        <summand weight="0.5" baseVector="em"/>
                        <summand weight="-0.5" baseVector="ep"/>
                    </equation>
                </plusMinusToZeroInf>
            </transformations>
        </definition>
        <description>
            <short value="5d conformal GA" />
            <long value="Base vectors: e1,e2,e3,einf,e0. Signature: {1,1,1,1,-1}. Represents points, lines, circles, planes and spheres"/>
        </description>
    </algebra>
    
    <algebra name="6d">
        <definition>
            <bases>
                <zeroInf>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                    <baseVector name="e5"/>
                    <baseVector name="e6"/>
                </zeroInf>
                <plusMinus>
                    <baseVector name="1"/>
                    <baseVector name="e1"/>
                    <baseVector name="e2"/>
                    <baseVector name="e3"/>
                    <baseVector name="e4"/>
                    <baseVector name="e5"/>
                    <baseVector name="e6"/>
                </plusMinus>
            </bases>
            <signature>
                <square baseVector="e1" value="1"/>
